name: "Enforce Branch Naming Convention"
on: [push]
jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
    - name: Check Branch Name
      run: |
        if [[ "$GITHUB_REF" == "refs/heads/main" ]] || [[ "$GITHUB_REF" =~ ^refs/heads/(feature|bug|exercise)/ ]]; then
          echo "Branch naming convention passed."
        else
          echo "Branch names must be 'main' or prefixed with 'feature/', 'bug/', or 'exercise/'."
          exit 1
        fi
